# Generated by Django 4.1.7 on 2023-03-29 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("attendees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountVO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
